---
- name: Install repo packages
  community.general.pacman:
    name:
      - gamemode
      - mangohud
      - steam
      - vulkan-tools
  become: false

- name: Install AUR packages
  community.general.pacman:
    name:
      - gpu-screen-recorder-git
    executable: paru
  become: true
  become_user: "{{ user }}"
