---
- name: Import RPM Fusion repositories (Free and Non-Free)
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
  become: false

- name: Install packages
  ansible.builtin.dnf:
    name:
      - mangohud
      - steam
      - vulkan-tools
  become: false
