---
- name: Include tasks
  ansible.builtin.include_tasks: "packages/{{ ansible_distribution | lower }}.yml"

- name: Get path of zsh
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: Ensure user shell is set to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
