# Set reasonable defaults and limits for quantum (latency/buffer size),
#  otherwise applications can end up with absurdly low values.
context.properties = {
    default.clock.quantum = 1024

    # 512 @ 48000 Hz = 10.6ms
    # Default value of 32 = 0.67ms which is WAY too low!
    default.clock.min-quantum = 512

    default.clock.max-quantum = 2048
}
