---
- name: Ensure mpd package is installed
  package:
    name: mpd
    state: present
  become: yes

- name: Ensure the mpd user socket is enabled and started
  systemd:
    name: mpd.socket
    scope: user
    enabled: yes
    state: started
