# Set reasonable defaults and limits for quantum (latency/buffer size),
#  otherwise applications can end up with absurdly low values.
pulse.properties = {
    pulse.default.req = 1024/48000

    # Minimum of 512 @ 48000 Hz = 10.6ms
    # Default value of 32 = 0.67ms which is WAY too low!
    pulse.min.req = 512/48000
    pulse.min.quantum = 512/48000

    pulse.max.quantum = 2048/48000
}
