#############################################
###   PLAYBOOK - CONFIGURE LOCAL SYSTEM   ###
#############################################
---
- name: Configure Local System
  hosts: localhost
  vars:
    user: "{{ lookup('ansible.builtin.env', 'SUDO_USER') }}"
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
  roles:
    - gui
    - neovim
    - ssh-client
    - zsh
