---
- name: Install packages
  community.general.pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - realtime-privileges
      - wireplumber
  become: false

- name: Add user to 'realtime' group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: realtime
    append: true
  become: false
