---
- name: Ensure openssh package is installed
  community.general.pacman:
    name: openssh
    state: present
  become: false

- name: Ensure SSH client socket directory exists
  ansible.builtin.file:
    path: "{{ home }}/.ssh/sockets"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory
