---
- name: Include tasks
  ansible.builtin.include_tasks: "packages/{{ ansible_distribution | lower }}.yml"

- name: Ensure SSH client socket directory exists
  ansible.builtin.file:
    path: "{{ home }}/.ssh/sockets"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory
