---
- name: Ensure openssh package is installed
  package:
    name: openssh
    state: present
  become: yes

- name: Ensure SSH client socket directory exists
  file:
    path: "{{ ansible_user_dir }}/.ssh/sockets"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0700
    state: directory
