---
- name: Install repo packages
  community.general.pacman:
    name:
      - alacritty
      - hyprland
      - hyprpaper
      - mpd
      - firefox
      - wofi
  become: false

- name: Install waybar-hyprland from the AUR
  community.general.pacman:
    name: waybar-hyprland
    executable: paru
    become: false
